import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';

import Button from '../Button';

export default {
  title: 'Button',
  component: Button,
  subcomponents: { Button },
  argTypes: {},
} as ComponentMeta<typeof Button>;

export const Primary: ComponentStory<typeof Button> = () => (
  <>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        primary
        variant="solid"
      />
      <Button 
        size="medium"
        text="Button"
        primary
        variant="solid"
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="solid"
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="solid"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        primary
        variant="outline"
      />
      <Button 
        size="medium"
        text="Button"
        primary
        variant="outline"
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="outline"
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="outline"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        primary
        variant="ghost"
      />
      <Button 
        size="medium"
        text="Button"
        primary
        variant="ghost"
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="ghost"
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="ghost"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        primary
        variant="solid"
        round
      />
      <Button 
        size="medium"
        text="Button"
        primary
        variant="solid"
        round
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="solid"
        round
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="solid"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        primary
        variant="outline"
        round
      />
      <Button 
        size="medium"
        text="Button"
        primary
        variant="outline"
        round
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="outline"
        round
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="outline"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        primary
        variant="ghost"
        round
      />
      <Button 
        size="medium"
        text="Button"
        primary
        variant="ghost"
        round
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="ghost"
        round
      />
      <Button
        size="large"
        text="Button"
        primary
        variant="ghost"
        round
        disabled
      />
    </div>
  </>
);
Primary.storyName = 'Primary Variant';

export const Secondary: ComponentStory<typeof Button> = () => (
  <>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        round
        disabled
      />
    </div>
  </>
);
Secondary.storyName = "Secondary Variant";

export const Success: ComponentStory<typeof Button> = () => (
  <>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        status="success"
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        status="success"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="success"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="success"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        status="success"
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        status="success"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="success"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="success"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        status="success"
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        status="success"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="success"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="success"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        status="success"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        status="success"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="success"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="success"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        status="success"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        status="success"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="success"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="success"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        status="success"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        status="success"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="success"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="success"
        round
        disabled
      />
    </div>
  </>
);
Success.storyName = "Success Status Variant";

export const Error: ComponentStory<typeof Button> = () => (
  <>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        status="error"
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        status="error"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="error"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="error"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        status="error"
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        status="error"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="error"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="error"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        status="error"
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        status="error"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="error"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="error"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        status="error"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        status="error"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="error"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="error"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        status="error"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        status="error"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="error"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="error"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        status="error"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        status="error"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="error"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="error"
        round
        disabled
      />
    </div>
  </>
);
Error.storyName = "Error Status Variant";

export const Warning: ComponentStory<typeof Button> = () => (
  <>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        status="warning"
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        status="warning"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="warning"
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="warning"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        status="warning"
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        status="warning"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="warning"
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="warning"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        status="warning"
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        status="warning"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="warning"
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="warning"
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="solid"
        status="warning"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="solid"
        status="warning"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="warning"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="solid"
        status="warning"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="outline"
        status="warning"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="outline"
        status="warning"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="warning"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="outline"
        status="warning"
        round
        disabled
      />
    </div>
    <div className="storybook-div">
      <Button
        size="small"
        text="Button"
        variant="ghost"
        status="warning"
        round
      />
      <Button 
        size="medium"
        text="Button"
        variant="ghost"
        status="warning"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="warning"
        round
      />
      <Button
        size="large"
        text="Button"
        variant="ghost"
        status="warning"
        round
        disabled
      />
    </div>
  </>
);
Warning.storyName = "Warning Status Variant";
